include:
  - dotnet_runtime: win-x64
    vsce_platform: win32-x64
    os: windows-latest
  - dotnet_runtime: linux-x64
    vsce_platform: linux-x64
    os: ubuntu-latest
  - dotnet_runtime: linux-arm64
    vsce_platform: linux-arm64
    os: ubuntu-latest
  - dotnet_runtime: osx-x64
    vsce_platform: darwin-x64
    os: macos-latest
  - dotnet_runtime: osx-arm64
    vsce_platform: darwin-arm64
    os: macos-latest