name: Contextive Publish
on:
  release:
    types: [published]
  
env:
  dotnet-version: '7.0.x'
  
jobs:
  get-matrix:
    uses: ./.github/workflows/get-matrix.yml
    with:
      matrix-path: .github/release-matrix.yml

  build-test-publish:
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-matrix.outputs.matrix) }}
    uses: ./.github/workflows/contextive-runtime-publish.yml
    with:
      dotnet_runtime: ${{ matrix.dotnet_runtime }}
      os: ${{ matrix.os }}
      vsce_platform: ${{ matrix.vsce_platform }}
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      VSCE_PAT: ${{ secrets.VSCE_PAT }}

