name: Contextive
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/contextive.yml'
      - '.github/actions/**'
env:
  DOTNET_VERSION: '7.0.x'
jobs:
  language-server:
    name: Language Server
    strategy:
      fail-fast: false
      matrix:
        include:
          - dotnet_runtime: win-x64
            os: windows-latest
          - dotnet_runtime: linux-x64
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/init-dotnet

      - name: Build
        id: build
        run: dotnet fsi language-server/build.fsx -- -r ${{ matrix.dotnet_runtime }}
        working-directory: src

      - name: Language Server Artifact
        uses: actions/upload-artifact@v3
        if: runner.os == 'Linux'
        with:
          name: Contextive.LanguageServer-${{matrix.dotnet_runtime}}
          path: ${{ steps.build.outputs.artifact-path }}

      - uses: ./.github/actions/upload-reports
        if: always()
        with:
          name: 'Contextive Language Server'
          reporter: dotnet-trx

  vscode:
    name: VsCode Extension
    runs-on: ubuntu-latest
    needs: language-server
    env:
      dotnet_runtime: linux-x64
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./.github/actions/init-dotnet

      - name: Language Server Artifact
        uses: actions/download-artifact@v3
        with:
          name: Contextive.LanguageServer-${{ env.dotnet_runtime }}
          path: src/

      - name: Build
        run: dotnet fsi vscode/build.fsx -- -r ${{ env.dotnet_runtime }}
        working-directory: src

      - uses: ./.github/actions/upload-reports
        if: always()
        with:
          name: 'Contextive VsCode Extension'
          reporter: java-junit