name: Contextive
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/contextive.yml'
      - '.github/workflows/contextive-runtime-build.yml'
      - '.github/workflows/get-matrix.yml'
      - '.github/build-matrix.yml'
      - '.github/actions/**'
env:
  DOTNET_VERSION: '7.0.x'

jobs:
  get-matrix:
    uses: ./.github/workflows/get-matrix.yml
    with:
      matrix-path: .github/build-matrix.yml

  build-test:
    needs: get-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-matrix.outputs.matrix) }}
    uses: ./.github/workflows/contextive-runtime-build.yml
    with:
      dotnet_runtime: ${{ matrix.dotnet_runtime }}
      os: ${{ matrix.os }}