name: Contextive Release
on: workflow_dispatch    

env:
  dotnet-version: '8.0.x'
jobs:
  build-and-test:
    name: 'Release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: ./.github/actions/init-dotnet

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: dotnet fsi release.fsx
        working-directory: src
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}