name: Contextive
on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/contextive.yml'
      - '.github/workflows/contextive-runtime-build.yml'
      - '.github/workflows/get-matrix.yml'
      - '.github/build-matrix.yml'
      - '.github/actions/**'
env:
  DOTNET_VERSION: '8.0.x'

jobs:
  get-matrix:
    uses: ./.github/workflows/get-matrix.yml
    with:
      matrix-path: .github/build-matrix.yml

  build-test-per-runtime:
    needs: get-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-matrix.outputs.matrix) }}
    uses: ./.github/workflows/contextive-runtime-build.yml
    with:
      dotnet_runtime: ${{ matrix.dotnet_runtime }}
      os: ${{ matrix.os }}
      vsce_platform: ${{matrix.vsce_platform }}

  # build-test-visualstudio:
  #   name: Visual Studio Extension
  #   needs:
  #     - language-server # TODO Confirm ID
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         persist-credentials: false

  #     - uses: ./.github/actions/init-dotnet

  #     - name: Language Server Artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: Contextive.LanguageServer-${{ inputs.dotnet_runtime }}
  #         path: src/

  #     - name: Build
  #       id: build
  #       run: dotnet fsi vscode/build.fsx -- -r ${{ inputs.dotnet_runtime }} --vsce-platform ${{ inputs.vsce_platform }}
  #       working-directory: src

  #     - name: Visual Studio Extension Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: Contextive-VisualStudio-Extension.vsix
  #         path: "src/visualstudio/**/*.vsix" # TODO: Confirm Path
  #         if-no-files-found: error

  #     # TODO: Uncomment once we have tests
  #     # - uses: ./.github/actions/upload-reports
  #     #   if: always()
  #     #   with:
  #     #     name: 'Contextive Visual Studio Extension'
  #     #     reporter: java-junit

  build-test-intellij:
    name: IntelliJ Plugin
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      # - name: Language Server Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: Contextive.LanguageServer-${{ inputs.dotnet_runtime }}
      #     path: src/

      - name: Build
        id: build
        run: ./gradlew build
        working-directory: src/intellij/contextive

      - name: IntelliJ Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Contextive-IntelliJ-Plugin
          path: "src/intellij/contextive/build/distributions/contextive-*.zip"

      - uses: ./.github/actions/upload-reports
        if: always()
        with:
          name: 'Contextive IntelliJ Plugin'
          reporter: java-junit