name: Get Matrix
on:
  workflow_call:
    inputs:
      matrix-path:
        required: true
        type: string
    outputs:
      matrix:
        description: "The first output string"
        value: ${{ jobs.get-matrix.outputs.matrix }}
        
jobs:

  get-matrix:
    name: "Load Build Matrix"
    outputs:
      matrix: ${{ steps.load-matrix.outputs.matrix }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: load-matrix
        name: Load Build Matrix
        run: |
          matrix="matrix=$(yq -P -o=json ${{ inputs.matrix-path }} | jq -c .)"
          echo $matrix
          echo $matrix >> $GITHUB_OUTPUT